---
- name: "Install AD_Join Packages"
  hosts: Home_Infrastructure
  become: true

  tasks:
  
  - name: Install and verify running service for sssd
    dnf:
      name: sssd
      state: started
  
  - name: Install and ensure existence for realmd
    dnf:
      name: realmd
      state: present

  - name: Install and verify running service oddjob
    dnf:
      name: oddjob
      state: started

  - name: Install and ensure existence for oddjob-mkhomedir
    dnf:
      name: oddjob-mkhomedir
      state: present

  - name: Install and ensure existence for adcli
    dnf:
      name: adcli
      state: present

  - name: Install and ensure existence for samba-common
    dnf:
      name: samba-common
      state: present    

  - name: Install and ensure existence for samba-common-tools
    dnf:
      name: samba-common-tools
      state: present

  - name: Install and ensure existence for krb5-workstation
    dnf:
      name: krb5-workstation
      state: present 

  - name: Install and ensure existence for openldap-clients
    dnf:
      name: openldap-clients
      state: present 

  - name: Install and ensure existence for policycoreutils-python
    dnf:
      name: policycoreutils-python
      state: present

  - name: configure sssd using survey values
    template:
      src: sssd.conf.j2
      dest: /etc/sssd/sssd.conf
  
  - name: restart sssd service and load new configs
    ansible.builtin.service:
        name: sshd
        state: restarted
        enabled: true
  
  